### ISSUE TITLE
in packet 3 file weeks should start on new line

### ISSUE THREAD

**Issue by TuncerKARAARSLAN-VB** [rifaterdemsahin/KubernetesTraining#1]
in packet 3 file weeks should start on new line

![image](https://github.com/user-attachments/assets/cae09fce-63f8-4ea0-874b-3e1404827921)

**Comment by rifaterdemsahin** [comment]
<img width="1397" alt="image" src="https://github.com/user-attachments/assets/0e083a9e-0435-419b-80c3-ed1ad1c1790b">

Fixed
